name: On Push to Main, Version and Tag For Release
on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:

  version-and-tag:
    name: Version and Tag
    uses: harmony-labs/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.5.0
    secrets: inherit
    with:
      useDeployKey: true
      runs-on: runs-on=${{ github.run_id }}/runner=1cpu-linux-x64/extras=s3-cache
      setup-runs-on: runs-on=${{ github.run_id }}/runner=1cpu-linux-x64/extras=s3-cache
      